name: Lint, Test & Build

on: [push]

jobs:
  builds:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:ci
      - name: Build
        run: npm run build:ci
      - name: Deploy
        run: "curl -X GET http://localhost:5000/deploy-dev-unit -H 'Content-Type: application/json'"
