name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: setup code
        run: echo "setup code"
      - name: starting test
        run: echo "test completed"
      - name: api deployment
        run: echo "deploy in pulumi"
      - name: multi script
        run: |
          node -v
          npm -v

